config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root("application#index")

  # Sign Up
  get("/auth/sign-up", to: "users#new", as: :new_user)
  post("/auth/sign-up", to: "users#create", as: :create_user)

  # Sign In
  get("/auth/sign-in", to: "sessions#new", as: :new_session)
  post("/auth/sign-in", to: "sessions#create", as: :create_session)
  delete("/auth/sign-out", to: "sessions#destroy", as: :destroy_session)

  # Kiosks
  get("/kiosks/:id", to: "kiosks#show", as: :show_kiosk)
  get("/kiosks", to: "kiosks#new", as: :new_kiosk)
  post("/kiosks", to: "kiosks#create", as: :create_kiosk)
  delete("/kiosks", to: "kiosks#destroy", as: :destroy_kiosk)

  # Purchases
  post("/cart", to: "purchases#create", as: :create_cart)
  get("/cart", to: "purchases#edit", as: :edit_cart)
  patch("/cart", to: "purchases#update", as: :update_cart)
  delete("/cart", to: "purchases#destroy", as: :destroy_cart)
  
  # Orders
  get("/orders", to: "orders#index", as: :index_order)
  get("/orders/:id", to: "orders#show", as: :show_order)

  # Products
  get("/foods-and-beverages", to: "products#new", as: :new_product)
  post("/foods-and-beverages", to: "products#create", as: :create_product)
  delete("/foods-and-beverages", to: "products#destroy", as: :destroy_product)

  # Menus
  get("/menus", to: "menus#new", as: :new_menu)
  post("/menus", to: "menus#create", as: :create_menu)
  delete("/menus", to: "menus#destroy", as: :destroy_menu)

  # API
  get("/api", to: "apis#index", as: :api)
  post("/api", to: "apis#index", as: :api_post)
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password()

    before_save() do
        self.email = self.email&.downcase()
    end

    has_many(:permissions, dependent: :destroy)
    has_many(:purchases, dependent: :destroy)
    has_many(:orders, dependent: :destroy)
    belongs_to(:address)

    validates(
        :email,
        uniqueness: true,
        length: {maximum: 100},
        format: {
            with: URI::MailTo::EMAIL_REGEXP,
            message: "must be valid"
        }
    )

    validates(
        :family_name,
        presence: true,
        length: {maximum: 25}
    )

    validates(
        :given_name,
        presence: true,
        length: {maximum: 50}
    )

    validates(
        :middle_name,
        length: {maximum: 25}
    )

    validates(
        :password,
        confirmation: true,
        length: {minimum: 6}
    )

    def full_name()
        name = [family_name, given_name].join(", ")
        name += middle_name ? " #{middle_name}" : ""
        return name
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action() do |controller|
        action = controller.action_name
        if ["new", "create"].include?(action) && @signed_in
            redirect_to(root_url())
        end
    end

    def new()
        @user = User.new(email: params.dig(:user, :email))
    end

    def create()
        pp = get_params()
        @user = User.new(
            email: pp[:email],
            family_name: pp[:family_name],
            given_name: pp[:given_name],
            middle_name: pp[:middle_name],
            password: pp[:password],
            password_confirmation: pp[:password_confirmation],
        )

        @address = Address.new(
            region: pp[:region],
            province: pp[:province],
            city: pp[:city],
            barangay: pp[:barangay],
            street: pp[:street],
        )

        if @address.valid?()
            @address.save()
            @user.update(address_id: @address.id)

            if @user.save()
                Utils.add_messages(
                    flash,
                    "Successful Account Registration",
                    "You may now try signing in your account.",
                    "positive",
                )
                redirect_to(new_session_url(session: {
                    email: @user.email
                }))
                return
            else
                @user.address.destroy()
            end
        end
        @user.validate()
        @user.errors.delete(:address)
        
        Utils.add_messages(
            flash.now,
            "Failed Account Registration",
            @user.errors.full_messages + @address.errors.full_messages,
            "negative",
        )
        render(:new, status: :unprocessable_entity)
    end

    private()

    def get_params()
        return params.require(:user).permit(
            :email,
            :family_name,
            :given_name,
            :middle_name,
            :region,
            :province,
            :city,
            :barangay,
            :street,
            :password,
            :password_confirmation
        )
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<% provide(:title, "Sign Up") %>
<%
%>
<%= render("partials/page_header", title: "Sign Up", subtitle: "New User? Setup an account in minutes!") %>
<div class="ui divider"></div>
<%= form_with(
    model: @user,
    id: "user-form",
    class: "ui form",
    url: create_user_path()
) do |form| %>
    <div class="field">
        <%= form.label(:email) %>
        <div class="ui left icon input">
            <%= form.email_field(:email, value: @user.email) %>
            <i class="at icon"></i>
        </div>
    </div>
    <div class="ui divider"></div>
    <div class="three fields">
        <div class="field">
            <%= form.label(:family_name, "Family Name") %>
            <div class="ui left icon input">
                <%= form.text_field(:family_name, value: nil) %>
                <i class="id badge icon"></i>
            </div>
        </div>
        <div class="field">
            <%= form.label(:given_name, "Given Name") %>
            <%= form.text_field(:given_name, value: nil) %>
        </div>
        <div class="field">
            <%= form.label(:middle_name, "Middle Name") %>
            <%= form.text_field(:middle_name, value: nil) %>
        </div>
    </div>
    <div class="ui divider"></div>
    <div class="two fields">
        <div class="field">
            <%= form.label(:region) %>
            <div id="region" class="ui selection dropdown">
                <%= form.hidden_field(:region) %>
                <i class="dropdown icon"></i>
                <div class="default text"></div>
                <div class="menu">
                </div>
            </div>
        </div>
        <div class="field">
            <%= form.label(:province) %>
            <div id="province" class="ui selection dropdown">
                <%= form.hidden_field(:province) %>
                <i class="dropdown icon"></i>
                <div class="default text"></div>
                <div class="menu">
                </div>
            </div>
        </div>
    </div>
    <div class="two fields">
        <div class="field">
            <%= form.label(:city) %>
            <div id="city" class="ui selection dropdown">
                <%= form.hidden_field(:city) %>
                <i class="dropdown icon"></i>
                <div class="default text"></div>
                <div class="menu">
                </div>
            </div>
        </div>
        <div class="field">
            <%= form.label(:barangay) %>
            <%= form.text_field(:barangay, value: nil) %>
        </div>
    </div>
    <div class="field">
        <%= form.label(:street) %>
        <div class="ui left icon input">
            <%= form.text_field(:street, value: nil) %>
            <i class="marker icon"></i>
        </div>
    </div>
    <div class="ui divider"></div>
    <div class="two fields">
        <div class="field">
            <%= form.label(:password) %>
            <div class="ui left icon input">
                <%= form.password_field(:password) %>
                <i class="key icon"></i>
            </div>
        </div>
        <div class="field">
            <%= form.label(:password_confirmation, "Password Confirmation") %>
            <%= form.password_field(:password_confirmation) %>
        </div>
    </div>
    <div class="ui right aligned fitted basic segment">
        <div class="ui buttons">
            <%= link_to("Sign In", new_session_path(), class: "ui button") %>
            <div class="or"></div>
            <%= form.submit("Submit", class: "ui green button") %>
        </div>
    </div>
<% end %>