config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root("application#index")

  # Sign Up
  get("/auth/sign-up", to: "users#new", as: :new_user)
  post("/auth/sign-up", to: "users#create", as: :create_user)

  # Sign In
  get("/auth/sign-in", to: "sessions#new", as: :new_session)
  post("/auth/sign-in", to: "sessions#create", as: :create_session)
  delete("/auth/sign-out", to: "sessions#destroy", as: :destroy_session)

  # Kiosks
  get("/kiosks/:id", to: "kiosks#show", as: :show_kiosk)
  get("/kiosks", to: "kiosks#new", as: :new_kiosk)
  post("/kiosks", to: "kiosks#create", as: :create_kiosk)
  delete("/kiosks", to: "kiosks#destroy", as: :destroy_kiosk)

  # Purchases
  post("/cart", to: "purchases#create", as: :create_cart)
  get("/cart", to: "purchases#edit", as: :edit_cart)
  patch("/cart", to: "purchases#update", as: :update_cart)
  delete("/cart", to: "purchases#destroy", as: :destroy_cart)
  
  # Orders
  get("/orders", to: "orders#index", as: :index_order)
  get("/orders/:id", to: "orders#show", as: :show_order)

  # Products
  get("/foods-and-beverages", to: "products#new", as: :new_product)
  post("/foods-and-beverages", to: "products#create", as: :create_product)
  delete("/foods-and-beverages", to: "products#destroy", as: :destroy_product)

  # Menus
  get("/menus", to: "menus#new", as: :new_menu)
  post("/menus", to: "menus#create", as: :create_menu)
  delete("/menus", to: "menus#destroy", as: :destroy_menu)

  # API
  get("/api", to: "apis#index", as: :api)
  post("/api", to: "apis#index", as: :api_post)
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
    before_action() do |controller|
        action = controller.action_name
        if ["edit", "new", "create", "update", "destroy"].include?(action) && !@signed_in
            redirect_to(new_session_url())
        end
        
        @purchase = Purchase.new()
        purchases = Purchase.where(user_id: @signed_in.id).order(created_at: :asc)
        @purchases = purchases.where("order_id is null")
        @ptotal = (@purchases.map() {|p| p.total}).sum()
        @opurchases = purchases.where("order_id is not null").page(params[:page] || 1).per(params[:count] || 10)
    end

    def create()
        pp = get_params()
        ref = params[:ref]
        errs = []
        items = []

        begin
            items = pp[:orders].split(",").map() {|i| i.split("-")}.map() do |i|
                p = @purchases.find_by(user_id: @signed_in.id, menu_id: i.first)
                if !p
                    p = Purchase.new(
                        user_id: @signed_in.id,
                        menu_id: i.first,
                        quantity: i.last
                    )
                else
                    p.update(quantity: p.quantity + i.last.to_i)
                end
                p
            end
        rescue
            items = []
            errs << "Cart Purchases are invalid"
        end

        if items.length == 0
            errs << "Must at least have one Purchase"
        else
            for item in items
                if !item.save()
                    errs << "Cart Purchases are invalid"
                    break
                end
            end
        end

        if errs.length == 0
            Utils.add_messages(
                flash,
                "Successful Cart Addition",
                "The purchase has been added to cart.",
                "positive",
            )
            if !ref
                redirect_to(edit_cart_url())
            else
                redirect_to(ref)
            end
            return
        else
            if !ref
                Utils.add_messages(
                    flash.now,
                    "Failed Cart Addition",
                    errs,
                    "negative",
                )
                render(:edit, status: :unprocessable_entity)
            else
                Utils.add_messages(
                    flash,
                    "Failed Cart Addition",
                    errs,
                    "negative",
                )
                redirect_to(ref)
            end
        end
    end

    def edit()
    end

    def update()
        orders = get_params()[:orders].split(",").map() do |o|
            @purchases.find_by(id: o)
        end
        orders = orders.compact

        address = Address.new()
        order = Order.new()

        errs = []

        if orders.length == 0
            errs << "Purchases must be checked first before checking out"
        else
            address.update(
                region: @signed_in.address.region,
                province: @signed_in.address.province,
                city: @signed_in.address.city,
                barangay: @signed_in.address.barangay,
                street: @signed_in.address.street,
            )
            address.save()

            order.update(
                user_id: @signed_in.id,
                address_id: address.id
            )
            if order.save()
                for o in orders
                    o.update(order_id: order.id, price: o.total)
                    if !o.save()
                        errs << "Purchases cannot be processed"
                    end
                end
            else
                errs << "Order cannot be created"
            end

            if errs.length == 0
                Utils.add_messages(
                    flash,
                    "Successful Order",
                    "Your purchases have been ordered",
                    "positive",
                )
                redirect_to(edit_cart_url())
            else
                order.address.destroy()
                order.destroy()

                for o in orders
                    o.update(order_id: nil, price: 0)
                    o.save()
                end

                Utils.add_messages(
                    flash.now,
                    "Failed Order",
                    errs,
                    "negative",
                )
                render(:edit, status: :unprocessable_entity)
            end
        end
    end

    def destroy()
    end

    private()

    def get_params()
        return params.require(:purchase).permit(
            :orders
        )
    end
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/views/purchases/edit.html.erb
<% provide(:title, "Cart") %>
<%
%>
<%= render("partials/page_header", title: "Cart", subtitle: "Manage your purchases.") %>
<div class="ui divider"></div>

<%= form_with(
    model: @purchase,
    id: "purchase-form",
    class: "ui form",
    method: :patch,
    url: update_cart_path()
) do |form| %>
    <%= form.hidden_field(:orders) %>
    <%= hidden_field_tag(:selected, "") %>
    
    <table class="ui very basic selectable celled mini table">
        <thead>
            <tr>
                <th colspan="5" class="right aligned">
                    <button class="ui tiny compact button select all" data-select-type="all" title="Select all" type="button">
                        All
                    </button>
                    <button class="ui tiny compact button select none" data-select-type="none" title="Deselect all" type="button">
                        None
                    </button>
                    <button class="ui tiny compact button select inverse" data-select-type="inverse" title="Invert selection" type="button">
                        Invert
                    </button>
                    <% if false %>
                        <a href="#" class="ui tiny compact icon button" title="View selected">
                            <i class="eye icon"></i>
                        </a>
                        <a href="#" class="ui tiny compact icon button" title="Edit selected">
                            <i class="edit icon"></i>
                        </a>
                        <a href="#" class="ui tiny compact icon button" title="Delete selected">
                            <i class="trash alternate icon"></i>
                        </a>
                    <% end %>
                </th>
            </tr>
            <tr>
                <th>
                    <div class="ui fitted checkbox">
                        <input class="selector main" type="checkbox" data-main-selector-id="0"><label></label>
                    </div>
                </th>
                <th>Item</th>
                <th>Price</th>
                <th>Quantity</th>
                <th>Total</th>
            </tr>
        </thead>
        <tbody>
            <% for p in @purchases %>
                <tr>
                    <td class="collapsing">
                        <div class="ui fitted checkbox">
                            <input class="selector" value="<%= p.id %>" type="checkbox" data-selector-id="0"><label></label>
                        </div>
                    </td>
                    <td>
                        <h6 class="ui image header">
                            <img src="/images/avatar2/small/lindsay.png" class="ui mini rounded image">
                            <div class="content">
                                <%= link_to(p.menu.name, "#") %>
                            </div>
                            </div>
                        </h6>
                    </td>
                    <td class="collapsing">&#x20B1;<%= number_with_precision(p.menu.price, precision: 2) %></td>
                    <td style="width: 17%">
                        <%= number_field_tag(nil, p.quantity, min: 1, data: {
                            "purchase-id" => p.id,
                            "purchase-price" => p.menu.price,
                            "purchase-total" => p.total,
                        }, class: "purchase-quantity") %>
                    </td>
                    <td class="collapsing">&#x20B1;<span class="purchase-total"><%= number_with_precision(p.total, precision: 2) %></span></td>
                </tr>
            <% end %>
            <% if @purchases.length == 0 %>
                <tr><td colspan="5" class="center aligned">No entry</td></tr>
            <% end %>
        </tbody>
        <tfoot>
            <tr>
                <td colspan="4" class="right aligned">
                    <h3 class="ui header">Grand Total</h3>
                </td>
                <td>
                    <h3 class="ui header">&#x20B1;<span class="purchase-grand-total"><%= number_with_precision(@ptotal, precision: 2) %></span></h3>
                </td>
            </tr>
        </tfoot>
    </table>
    
    <div class="ui right aligned fitted basic segment">
        <div class="ui buttons">
            <%= link_to("Cancel", destroy_cart_path(), class: "ui button", data: {
                turbo_method: :delete,
                turbo_confirm: "Are you sure you want to cancel your purchases?",
            }) %>
            <div class="or"></div>
            <%= form.submit("Checkout", class: "ui green button") %>
        </div>
    </div>
<% end %>