config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root("application#index")

  # Sign Up
  get("/auth/sign-up", to: "users#new", as: :new_user)
  post("/auth/sign-up", to: "users#create", as: :create_user)

  # Sign In
  get("/auth/sign-in", to: "sessions#new", as: :new_session)
  post("/auth/sign-in", to: "sessions#create", as: :create_session)
  delete("/auth/sign-out", to: "sessions#destroy", as: :destroy_session)

  # Kiosks
  get("/kiosks/:id", to: "kiosks#show", as: :show_kiosk)
  get("/kiosks", to: "kiosks#new", as: :new_kiosk)
  post("/kiosks", to: "kiosks#create", as: :create_kiosk)
  delete("/kiosks", to: "kiosks#destroy", as: :destroy_kiosk)

  # Purchases
  post("/cart", to: "purchases#create", as: :create_cart)
  get("/cart", to: "purchases#edit", as: :edit_cart)
  patch("/cart", to: "purchases#update", as: :update_cart)
  delete("/cart", to: "purchases#destroy", as: :destroy_cart)
  
  # Orders
  get("/orders", to: "orders#index", as: :index_order)
  get("/orders/:id", to: "orders#show", as: :show_order)

  # Products
  get("/foods-and-beverages", to: "products#new", as: :new_product)
  post("/foods-and-beverages", to: "products#create", as: :create_product)
  delete("/foods-and-beverages", to: "products#destroy", as: :destroy_product)

  # Menus
  get("/menus", to: "menus#new", as: :new_menu)
  post("/menus", to: "menus#create", as: :create_menu)
  delete("/menus", to: "menus#destroy", as: :destroy_menu)

  # API
  get("/api", to: "apis#index", as: :api)
  post("/api", to: "apis#index", as: :api_post)
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to(:user)
    belongs_to(:address)
    has_many(:purchases, dependent: :destroy)

    def price()
        return (purchases.map() {|p| p.total}).sum()
    end

    def identifier()
        return "#{user.id}-#{created_at.to_i}"
    end
    
    def kiosks()
        return purchases.select("kiosks.name").joins("left join menus on purchases.menu_id = menus.id").joins("left join kiosks on menus.kiosk_id = kiosks.id").order("kiosks.name asc").map() {|r| r.name}
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    before_action() do |controller|
        action = controller.action_name
        if ["index", "new", "create", "destroy"].include?(action) && !@signed_in
            redirect_to(new_session_url())
        end
        
        @order = Order.new()
        @orders = Order.where(user_id: @signed_in&.id || -1).page(params[:page] || 1).per(params[:count] || 10)
    end

    def show()
        @order = Order.find_by(id: params[:id])
        @purchases = @order.purchases.page(params[:page] || 1).per(params[:count] || 10)
        @id = @order.identifier
    end

    def index()
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/index.html.erb
<% provide(:title, "Orders") %>
<%
    subtitle = "Manage your orders."
%>
<%= render("partials/page_header", title: "Orders", subtitle: subtitle) %>
<div class="ui divider"></div>
<div class="ui two cards">
    <% for o in @orders %>
        <div class="card">
            <div class="content">
                <%= link_to(o.identifier, show_order_path(o.id), class: "header") %>
                <div class="meta">
                    <span class="time" title="<%= o.created_at.to_formatted_s(:long) %>"><%= time_ago_in_words(o.created_at) %> ago</span>
                </div>
                <div class="description">
                    <%= (o.purchases.map() {|p| p.menu.name}).join(", ") %>
                </div>
            </div>
            <div class="extra content">
                <a href="<%= show_order_path(o.id) %>">
                    <i class="ruble sign icon"></i>
                    &#x20B1;<%= number_with_precision(o.price, precision: 2) %>
                </a>
            </div>
        </div>
    <% end %>
</div>

app/views/orders/show.html.erb
<% provide(:title, "Order | #{@id}") %>
<%
    price = number_with_precision(@order.price, precision: 2)
%>
<h2 class="ui center aligned header">
    <div class="content">
        <%= @id %>
        <div class="sub header" title="">&#x20B1;<%= price %></div>
    </div>
</h2>

<h3 class="ui header">
  Details
</h3>
<div class="ui basic fitted segment">
    <div class="ui list">
        <div class="item">
            <div class="header">Identifier</div>
            <%= @order.identifier %>
        </div>
    </div>
    <div class="ui very relaxed horizontal list">
        <div class="item">
            <div class="header">Date Placed</div>
            <%= @order.created_at.to_formatted_s(:long) %>
        </div>
        <div class="item">
            <div class="header">Total</div>
            &#x20B1;<%= price %>
        </div>
    </div>
    <div class="ui list">
        <div class="item">
            <div class="header">Merchants</div>
            <%= @order.kiosks.join(", ") %>
        </div>
    </div>
</div>

<h3 class="ui header">
  Recipient
</h3>
<div class="ui basic fitted segment">
    <div class="ui list">
        <div class="item">
            <div class="header">Name</div>
            <%= @order.user.full_name %>
        </div>
    </div>
    <div class="ui list">
        <div class="item">
            <div class="header">Address</div>
            <%= @order.address.full %>
        </div>
    </div>
</div>

<h3 class="ui header">
  Purchases
</h3>
<div class="ui basic fitted segment">
    <table class="ui selectable celled mini table">
        <thead>
            <tr>
                <th colspan="5" class="right aligned">
                    <button class="ui tiny compact button select all" data-select-type="all" title="Select all" type="button">
                        All
                    </button>
                    <button class="ui tiny compact button select none" data-select-type="none" title="Deselect all" type="button">
                        None
                    </button>
                    <button class="ui tiny compact button select inverse" data-select-type="inverse" title="Invert selection" type="button">
                        Invert
                    </button>
                </th>
            </tr>
            <tr>
                <th>
                    <div class="ui fitted checkbox">
                        <input class="selector main" type="checkbox" data-main-selector-id="0"><label></label>
                    </div>
                </th>
                <th>Name</th>
                <th>Price</th>
                <th>Quantity</th>
                <th>Total</th>
            </tr>
        </thead>
        <tbody>
            <% for p in @purchases
                m = p.menu
            %>
                <tr>
                    <td class="collapsing">
                        <div class="ui fitted checkbox">
                            <input class="selector" value="<%= m.id %>" type="checkbox" data-selector-id="0"><label></label>
                        </div>
                    </td>
                    <td>
                        <h6 class="ui image header">
                            <img src="/images/avatar2/small/lindsay.png" class="ui mini rounded image">
                            <div class="content">
                                <%= link_to(m.name, "#") %>
                            </div>
                            </div>
                        </h6>
                    </td>
                    <td>&#x20B1;<%= number_with_precision(p.price, precision: 2) %></td>
                    <td><%= p.quantity %></td>
                    <td>&#x20B1;<%= number_with_precision(p.final_total, precision: 2) %></td>
                </tr>
            <% end %>
            <% if @purchases.length == 0 %>
                <tr><td colspan="5" class="center aligned">No entry</td></tr>
            <% end %>
        </tbody>
        <% if @purchases.total_pages > 1 %>
            <tfoot>
                <tr>
                    <th colspan="4" class="center aligned">
                        <%= render("partials/pagination", page: @purchases.current_page, pages: @purchases.total_pages, count: @purchases.size, size: "mini") %>
                    </th>
                </tr>
            </tfoot>
        <% end %>
    </table>
</div>