config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root("application#index")

  # Sign Up
  get("/auth/sign-up", to: "users#new", as: :new_user)
  post("/auth/sign-up", to: "users#create", as: :create_user)

  # Sign In
  get("/auth/sign-in", to: "sessions#new", as: :new_session)
  post("/auth/sign-in", to: "sessions#create", as: :create_session)
  delete("/auth/sign-out", to: "sessions#destroy", as: :destroy_session)

  # Kiosks
  get("/kiosks/:id", to: "kiosks#show", as: :show_kiosk)
  get("/kiosks", to: "kiosks#new", as: :new_kiosk)
  post("/kiosks", to: "kiosks#create", as: :create_kiosk)
  delete("/kiosks", to: "kiosks#destroy", as: :destroy_kiosk)

  # Purchases
  post("/cart", to: "purchases#create", as: :create_cart)
  get("/cart", to: "purchases#edit", as: :edit_cart)
  patch("/cart", to: "purchases#update", as: :update_cart)
  delete("/cart", to: "purchases#destroy", as: :destroy_cart)
  
  # Orders
  get("/orders", to: "orders#index", as: :index_order)
  get("/orders/:id", to: "orders#show", as: :show_order)

  # Products
  get("/foods-and-beverages", to: "products#new", as: :new_product)
  post("/foods-and-beverages", to: "products#create", as: :create_product)
  delete("/foods-and-beverages", to: "products#destroy", as: :destroy_product)

  # Menus
  get("/menus", to: "menus#new", as: :new_menu)
  post("/menus", to: "menus#create", as: :create_menu)
  delete("/menus", to: "menus#destroy", as: :destroy_menu)

  # API
  get("/api", to: "apis#index", as: :api)
  post("/api", to: "apis#index", as: :api_post)
end

app/models/kiosk.rb
class Kiosk < ApplicationRecord
    before_save() do
        self.email = self.email&.downcase()
    end

    belongs_to(:address)
    has_many(:menus, dependent: :destroy)

    validates(
        :name,
        presence: true,
        uniqueness: true,
        length: {maximum: 100}
    )

    validates(
        :email,
        length: {maximum: 100},
        format: {
            with: URI::MailTo::EMAIL_REGEXP,
            message: "must be valid"
        }
    )

    validates(
        :mobile_number,
        format: {
            with: /[0-9]{11}/,
            message: "must be an 11-digit number"
        }
    )

    validates(
        :description,
        length: {maximum: 500}
    )
end

app/controllers/kiosks_controller.rb
class KiosksController < ApplicationController
    before_action() do |controller|
        action = controller.action_name
        if ["new", "create", "destroy"].include?(action) && !@signed_in
            redirect_to(new_session_url())
        end
        
        @kiosks = Kiosk.page(params[:page] || 1).per(params[:count] || 10)
    end

    def show()
        @kiosk = Kiosk.find_by(id: params[:id])
        @menus = @kiosk.menus.page(params[:page] || 1).per(params[:count] || 10)
        @name = @kiosk.name
    end

    def new()
        @kiosk = Kiosk.new()
    end

    def create()
        pp = get_params()
        @kiosk = Kiosk.new(
            name: pp[:name],
            email: pp[:email],
            mobile_number: pp[:mobile_number],
            description: pp[:description],
        )

        @address = Address.new(
            region: pp[:region],
            province: pp[:province],
            city: pp[:city],
            barangay: pp[:barangay],
            street: pp[:street],
        )

        if @address.valid?()
            @address.save()
            @kiosk.update(address_id: @address.id)

            if @kiosk.save()
                Utils.add_messages(
                    flash,
                    "Successful Kiosk Registration",
                    "The kiosk has been registered.",
                    "positive",
                )
                redirect_to(new_kiosk_url())
                return
            else
                @kiosk.address.destroy()
            end
        end
        @kiosk.validate()
        @kiosk.errors.delete(:address)

        Utils.add_messages(
            flash.now,
            "Failed Kiosk Registration",
            @kiosk.errors.full_messages + @address.errors.full_messages,
            "negative",
        )
        render(:new, status: :unprocessable_entity)
    end

    def destroy()
    end

    private()

    def get_params()
        return params.require(:kiosk).permit(
            :name,
            :email,
            :mobile_number,
            :region,
            :province,
            :city,
            :barangay,
            :street,
            :description,
            :images
        )
    end
end

app/helpers/kiosks_helper.rb
module KiosksHelper
end

app/views/kiosks/new.html.erb
<% provide(:title, "Kiosks") %>
<%
    if @customer && @client
        subtitle = "Manage your kiosks and view the other available kiosks."
    elsif @client
        subtitle = "Manage your kiosks."
    elsif @customer
        subtitle = "The available kiosks in your area."
    end
%>
<%= render("partials/page_header", title: "Kiosks", subtitle: subtitle) %>
<div class="ui divider"></div>
<% if @client %>
    <%= form_with(
        model: @kiosk,
        id: "kiosk-form",
        class: "ui form",
        url: create_kiosk_path()
    ) do |form| %>
        <div class="field">
            <%= form.label(:name, "Name") %>
            <div class="ui left icon input">
                <%= form.text_field(:name, value: nil) %>
                <i class="tag icon"></i>
            </div>
        </div>
        <div class="ui divider"></div>
        <div class="two fields">
            <div class="field">
                <%= form.label(:email) %>
                <div class="ui left icon input">
                    <%= form.email_field(:email) %>
                    <i class="at icon"></i>
                </div>
            </div>
            <div class="field">
                <%= form.label(:mobile_number, "Mobile Number") %>
                <%= form.text_field(:mobile_number, value: nil) %>
            </div>
        </div>
        <div class="ui divider"></div>
        <div class="two fields">
            <div class="field">
                <%= form.label(:region) %>
                <div id="region" class="ui selection dropdown">
                    <%= form.hidden_field(:region) %>
                    <i class="dropdown icon"></i>
                    <div class="default text"></div>
                    <div class="menu">
                    </div>
                </div>
            </div>
            <div class="field">
                <%= form.label(:province) %>
                <div id="province" class="ui selection dropdown">
                    <%= form.hidden_field(:province) %>
                    <i class="dropdown icon"></i>
                    <div class="default text"></div>
                    <div class="menu">
                    </div>
                </div>
            </div>
        </div>
        <div class="two fields">
            <div class="field">
                <%= form.label(:city) %>
                <div id="city" class="ui selection dropdown">
                    <%= form.hidden_field(:city) %>
                    <i class="dropdown icon"></i>
                    <div class="default text"></div>
                    <div class="menu">
                    </div>
                </div>
            </div>
            <div class="field">
                <%= form.label(:barangay) %>
                <%= form.text_field(:barangay, value: nil) %>
            </div>
        </div>
        <div class="field">
            <%= form.label(:street) %>
            <div class="ui left icon input">
                <%= form.text_field(:street, value: nil) %>
                <i class="marker icon"></i>
            </div>
        </div>
        <div class="ui divider"></div>
        <div class="field">
            <%= form.label(:description) %>
            <%= form.text_area(:description, rows: 3, value: nil) %>
        </div>
        <div class="field">
            <%= form.label(:images) %>
            <%= form.file_field(:images, multiple: true, class: "image-upload", accept: $VALID_IMAGE_UPLOAD) %>
        </div>
        <%= render("partials/image_preview") %>
        <div class="ui right aligned fitted basic segment">
            <%= form.submit("Register", class: "ui green button") %>
        </div>
    <% end %>

    <div class="ui divider"></div>
<% end %>

<%= hidden_field_tag(:selected, "") %>
<table class="ui selectable celled mini table">
    <thead>
        <% if @client %>
            <tr>
                <th colspan="4" class="right aligned">
                    <button class="ui tiny compact button select all" data-select-type="all" title="Select all" type="button">
                        All
                    </button>
                    <button class="ui tiny compact button select none" data-select-type="none" title="Deselect all" type="button">
                        None
                    </button>
                    <button class="ui tiny compact button select inverse" data-select-type="inverse" title="Invert selection" type="button">
                        Invert
                    </button>
                    <% if false %>
                        <a href="#" class="ui tiny compact icon button" title="View selected">
                            <i class="eye icon"></i>
                        </a>
                        <a href="#" class="ui tiny compact icon button" title="Edit selected">
                            <i class="edit icon"></i>
                        </a>
                        <a href="#" class="ui tiny compact icon button" title="Delete selected">
                            <i class="trash alternate icon"></i>
                        </a>
                    <% end %>
                </th>
            </tr>
        <% end %>
        <tr>
            <% if @client %>
                <th>
                    <div class="ui fitted checkbox">
                        <input class="selector main" type="checkbox" data-main-selector-id="0"><label></label>
                    </div>
                </th>
            <% end %>
            <th>Name</th>
            <th>Location</th>
            <th>Description</th>
        </tr>
    </thead>
    <tbody>
        <% for k in @kiosks %>
            <tr>
                <% if @client %>
                    <td class="collapsing">
                        <div class="ui fitted checkbox">
                            <input class="selector" value="1" type="checkbox" data-selector-id="0"><label></label>
                        </div>
                    </td>
                <% end %>
                <td>
                    <h6 class="ui image header">
                        <img src="/images/avatar2/small/lindsay.png" class="ui mini rounded image">
                        <div class="content">
                            <%= link_to(k.name, show_kiosk_path(k.id)) %>
                        </div>
                        </div>
                    </h6>
                </td>
                <td><%= k.address.city + ", " + k.address.province %></td>
                <td><%= "" %></td>
            </tr>
        <% end %>
        <% if @kiosks.length == 0 %>
            <tr><td colspan="<%= @client ? 4 : 3 %>" class="center aligned">No entry</td></tr>
        <% end %>
    </tbody>
    <% if @kiosks.total_pages > 1 %>
        <tfoot>
            <tr>
                <th colspan="4" class="center aligned">
                    <%= render("partials/pagination", page: @kiosks.current_page, pages: @kiosks.total_pages, count: @kiosks.size, size: "mini") %>
                </th>
            </tr>
        </tfoot>
    <% end %>
</table>

app/views/kiosks/show.html.erb
<% provide(:title, "Kiosks | #{@name}") %>
<%
%>
<h2 class="ui center aligned header">
    <div class="content">
        <%= @name %>
        <div class="sub header" title="Full Address"><%= [@kiosk.address.city, @kiosk.address.province].join(", ") %></div>
    </div>
</h2>

<h3 class="ui header">
  Details
</h3>
<div class="ui basic fitted segment">
    <div class="ui list">
        <div class="item">
            <div class="header">Address</div>
            <%= @kiosk.address.full %>
        </div>
    </div>
    <div class="ui very relaxed horizontal list">
        <div class="item">
            <div class="header">Email</div>
            <%= @kiosk.email %>
        </div>
        <div class="item">
            <div class="header">Mobile Number</div>
            <%= @kiosk.mobile_number %>
        </div>
    </div>
    <% if !@kiosk.description %>
        <div class="ui list">
            <div class="item">
                <div class="header">Description</div>
                <%= @kiosk.description %>
            </div>
        </div>
    <% end %>
</div>

<h3 class="ui header">
  Images
</h3>
<div id="image-previews-parent" class="ui basic fitted segment">
    <div class="image-previews">
        <% for i in 1..5 %>
            <div class="image-preview">
                <img src="https://via.placeholder.com/100x100.png">
            </div>
        <% end %>
    </div>
</div>


<h3 class="ui header">
  Menus
</h3>
<div class="ui basic fitted segment">
    <%= form_with(
        scope: :purchase,
        id: "kiosk-purchase-form",
        class: "ui form",
        url: create_cart_path(ref: show_kiosk_url(@kiosk.id))
    ) do |form| %>
        <%= hidden_field_tag(:selected, "") %>
        <%= form.hidden_field(:orders) %>

        <table class="ui selectable celled mini table">
            <thead>
                <tr>
                    <th colspan="4" class="right aligned">
                        <button class="ui tiny compact button select all" data-select-type="all" title="Select all" type="button">
                            All
                        </button>
                        <button class="ui tiny compact button select none" data-select-type="none" title="Deselect all" type="button">
                            None
                        </button>
                        <button class="ui tiny compact button select inverse" data-select-type="inverse" title="Invert selection" type="button">
                            Invert
                        </button>
                        <%= number_field_tag("", 1, id: "purchase-quantity", min: 1, max: 999, style: "width: 5em", title: "Quantity") %>
                        <button type="submit" class="ui tiny compact icon button" title="Add selected to Cart">
                            <i class="cart plus icon"></i>
                        </button>
                    </th>
                </tr>
                <tr>
                    <th>
                        <div class="ui fitted checkbox">
                            <input class="selector main" type="checkbox" data-main-selector-id="0"><label></label>
                        </div>
                    </th>
                    <th>Name</th>
                    <th>Items</th>
                    <th>Price</th>
                </tr>
            </thead>
            <tbody>
                <% for m in @menus %>
                    <tr>
                        <td class="collapsing">
                            <div class="ui fitted checkbox">
                                <input class="selector" value="<%= m.id %>" type="checkbox" data-selector-id="0"><label></label>
                            </div>
                        </td>
                        <td>
                            <h6 class="ui image header">
                                <img src="/images/avatar2/small/lindsay.png" class="ui mini rounded image">
                                <div class="content">
                                    <%= link_to(m.name, "#") %>
                                </div>
                                </div>
                            </h6>
                        </td>
                        <td><%= raw m.items.map() {|i|
                            "#{i.product.name} (#{i.quantity})"}.join(", ") %>
                        </td>
                        <td>&#x20B1;<%= number_with_precision(m.price, precision: 2) %></td>
                    </tr>
                <% end %>
                <% if @menus.length == 0 %>
                    <tr><td colspan="4" class="center aligned">No entry</td></tr>
                <% end %>
            </tbody>
            <% if @menus.total_pages > 1 %>
                <tfoot>
                    <tr>
                        <th colspan="4" class="center aligned">
                            <%= render("partials/pagination", page: @menus.current_page, pages: @menus.total_pages, count: @menus.size, size: "mini") %>
                        </th>
                    </tr>
                </tfoot>
            <% end %>
        </table>
    <% end %>
</div>